static unsigned computehash(const utf8* name);
static int hashLocate(struct HashTable* table, const utf8* name, struct HashEntry** prevp);
static void hashRemove(struct HashTable* table, struct HashEntry* prev, struct HashEntry* entry);
static void hashInsert(struct HashTable* table, struct HashEntry* prev, struct HashEntry* entry);
static void* hashwalk(struct HashTable* table);
static void hashwalkstop(void* walkstate);
static int hashnext(void* walkstate, struct HashEntry** ithentryp);
static Function* dictionaryLookup(TTM* ttm, const utf8* name);
static Function* dictionaryRemove(TTM* ttm, const utf8* name);
static int dictionaryInsert(TTM* ttm, Function* fcn);
static Charclass* charclassLookup(TTM* ttm, const utf8* name);
static Charclass* charclassRemove(TTM* ttm, const utf8* name);
static int charclassInsert(TTM* ttm, Charclass* cl);
static TTM* newTTM(struct Properties*);
static void freeTTM(TTM* ttm);
static void clearHashEntry(struct HashEntry* entry);
static Frame* pushFrame(TTM* ttm);
static void popFrame(TTM* ttm);
static void clearFrame(TTM* ttm, Frame* frame);
static void freeFramestack(TTM* ttm, Frame* stack, size_t stacksize);
static Function* newFunction(TTM* ttm);
static void freeFunction(TTM* ttm, Function* f);
static void clearDictionary(TTM* ttm, struct HashTable* dict);
static Charclass* newCharclass(TTM* ttm);
static void freeCharclass(TTM* ttm, Charclass* cl);
static void clearCharclasses(TTM* ttm, struct HashTable* charclasses);
static int charclassMatch(utf8* cp, utf8* charclass);
static TTMERR scan(TTM* ttm);
static TTMERR testfcnprefix(TTM* ttm, enum FcnCallCases* pfcncase);
static TTMERR scan1(TTM* ttm, utf8**);
static TTMERR collectargs(TTM* ttm, Frame** framep);
static TTMERR exec(TTM* ttm, Frame* frame);
static TTMERR call(TTM* ttm, Frame* frame, utf8* body);
static TTMERR processfcn(TTM* ttm);
static TTMERR printstring(TTM* ttm, const utf8* s8, TTMFILE* output);
static const char* print2len(VString* vs);
static const char* printsubseq(VString* vs, size_t argstart , size_t argend);
static utf8* printclean(const utf8* s8, char* ctrls, size_t* pfinallen);
static Function* getdictstr(TTM* ttm,const Frame* frame,size_t argi);
static void ttm_ap(TTM* ttm, Frame* frame);
static void ttm_cf(TTM* ttm, Frame* frame);
static void ttm_cr(TTM* ttm, Frame* frame);
static void ttm_ds(TTM* ttm, Frame* frame);
static void ttm_es(TTM* ttm, Frame* frame);
static void ttm_sc(TTM* ttm, Frame* frame);
static void ttm_ss(TTM* ttm, Frame* frame);
static void ttm_ss0(TTM* ttm, Frame* frame, size_t* segcountp);
static size_t ttm_mark1(TTM* ttm, VString* target, utf8* pattern, size_t mark);
static void ttm_cc(TTM* ttm, Frame* frame);
static void ttm_cn(TTM* ttm, Frame* frame);
static void ttm_sn(TTM* ttm, Frame* frame);
static void ttm_isc(TTM* ttm, Frame* frame);
static void ttm_scn(TTM* ttm, Frame* frame);
static void ttm_cp(TTM* ttm, Frame* frame);
static void ttm_cs(TTM* ttm, Frame* frame);
static void ttm_rrp(TTM* ttm, Frame* frame);
static void ttm_eos(TTM* ttm, Frame* frame);
static void ttm_gn(TTM* ttm, Frame* frame);
static void ttm_zlc(TTM* ttm, Frame* frame);
static void ttm_zlcp(TTM* ttm, Frame* frame);
static void ttm_flip(TTM* ttm, Frame* frame);
static void ttm_dcl0(TTM* ttm, Frame* frame, int negative);
static void ttm_dcl(TTM* ttm, Frame* frame);
static void ttm_dncl(TTM* ttm, Frame* frame);
static void ttm_ecl(TTM* ttm, Frame* frame);
static void ttm_ccl(TTM* ttm, Frame* frame);
static void ttm_scl(TTM* ttm, Frame* frame);
static void ttm_tcl(TTM* ttm, Frame* frame);
static void ttm_abs(TTM* ttm, Frame* frame);
static void ttm_ad(TTM* ttm, Frame* frame);
static void ttm_dv(TTM* ttm, Frame* frame);
static void ttm_dvr(TTM* ttm, Frame* frame);
static void ttm_mu(TTM* ttm, Frame* frame);
static void ttm_su(TTM* ttm, Frame* frame);
static void ttm_eq(TTM* ttm, Frame* frame);
static void ttm_gt(TTM* ttm, Frame* frame);
static void ttm_lt(TTM* ttm, Frame* frame);
static void ttm_eql(TTM* ttm, Frame* frame);
static void ttm_gtl(TTM* ttm, Frame* frame);
static void ttm_ltl(TTM* ttm, Frame* frame);
static void ttm_ps(TTM* ttm, Frame* frame);
static void ttm_rs(TTM* ttm, Frame* frame);
static void ttm_psr(TTM* ttm, Frame* frame);
static void ttm_cm(TTM* ttm, Frame* frame);
static void ttm_pf(TTM* ttm, Frame* frame);
static void ttm_names(TTM* ttm, Frame* frame);
static void ttm_exit(TTM* ttm, Frame* frame);
static void ttm_ndf(TTM* ttm, Frame* frame);
static void ttm_norm(TTM* ttm, Frame* frame);
static void ttm_time(TTM* ttm, Frame* frame);
static void ttm_xtime(TTM* ttm, Frame* frame);
static void ttm_ctime(TTM* ttm, Frame* frame);
static void ttm_tf(TTM* ttm, Frame* frame);
static void ttm_tn(TTM* ttm, Frame* frame);
static void ttm_argv(TTM* ttm, Frame* frame);
static void ttm_argc(TTM* ttm, Frame* frame);
static void ttm_classes(TTM* ttm, Frame* frame);
static void ttm_lf(TTM* ttm, Frame* frame);
static void ttm_uf(TTM* ttm, Frame* frame);
static void ttm_include(TTM* ttm, Frame* frame);
static void ttm_ttm_meta(TTM* ttm, Frame* frame);
static void ttm_ttm_info_name(TTM* ttm, Frame* frame);
static void ttm_ttm_info_class(TTM* ttm, Frame* frame);
static void ttm_ttm_info_string(TTM* ttm, Frame* frame);
static void ttm_ttm(TTM* ttm, Frame* frame);
static void defineBuiltinFunction1(TTM* ttm, struct Builtin* bin);
static void defineBuiltinFunctions(TTM* ttm);
static TTMERR execcmd(TTM* ttm, const char* cmd);
static void lockup(TTM* ttm);
static TTMERR collectescaped(TTM* ttm, VString* dst);
static const char* sv(Function* f);
static TTMERR peek(VString* vs, size_t n, utf8* cpa);
static void initglobals();
static void usage(const char* msg);
static TTMERR readline(TTM* ttm, TTMFILE* f, VString* buf);
static TTMERR readfile(TTM* ttm, const char* fname, VString* buf);
static struct Properties propertiesclone(struct Properties* props);
static void setproperty(const char* tag, const char* value, struct Properties* props);
static void resetproperty(struct Properties* props, const char* key, const struct Properties* dfalts);
static int u8sizec(utf8 c);
static int u8size(const utf8* cp);
static int u8validcp(utf8* cp);
static void ascii2u8(char c, utf8* u8);
static int u8equal(const utf8* c1, const utf8* c2);
static int memcpycp(utf8* dst, const utf8* src);
static int u8cpcount(const utf8* src, size_t n);
static const utf8* u8ithcp(const utf8* base, size_t n);
static int u8ith(const utf8* base, size_t n);
static const utf8* u8backup(const utf8* p0);
static int ttmgetc8(TTM* ttm, TTMFILE* f, utf8* cp8);
static int ttmnonl(TTM* ttm, TTMFILE* f, utf8* cp8);
static void ttmpushbackc(TTM* ttm, TTMFILE* f, utf8* cp8);
static int ttmputc8(TTM* ttm, const utf8* c8, TTMFILE* f);
static long long getRunTime(void);
static int timeofday(struct timeval *tv);
static long long getRunTime(void);
static int timeofday(struct timeval *tv);
static void xprintf(TTM*,const char* fmt,...);
static void vxprintf(TTM*,const char* fmt, va_list ap);

static TTMFILE* ttmopen(TTM* ttm, const char* fname, const char* mode);
static int ttmclose(TTM* ttm, TTMFILE* tfile);
static int ttmerror(TTM* ttm, TTMFILE* tfile);
static int ttmeof(TTM* ttm, TTMFILE* tfile);

static void dumpframe(TTM* ttm, Frame* frame);
static void dumpstack(TTM* ttm);
static void traceframe(TTM* ttm, Frame* frame, int traceargs);
static void trace1(TTM* ttm, int depth, int entering, int tracing);
static void trace(TTM* ttm, int entering, int tracing);
static void fail(TTM* ttm, TTMERR eno, int line);
static TTMERR failx(TTM* ttm, TTMERR eno, int line, const char* fmt, ...);
static TTMERR failxcxt(TTM* ttm, TTMERR eno, int line);
static const char* errstring(TTMERR err);

#ifdef GDB
static void dumpdict0(TTM*,struct HashTable* dict, int printvalues);
static void dumpnames(TTM* ttm);
static void dumpcharclasses(TTM* ttm);
static const utf8* printwithpos(VString* vs);
static const utf8* printwithpos(VString* vs);
#endif /*GDB*/

static char* debash(const char* s);

/* Hack to suppress compiler warnings about selected unused static functions */
static void
suppresswarnings(void)
{
    void* ignore;
    ignore = (void*)suppresswarnings;
    (void)ignore;
}
